### ISSUE TITLE
MyAnime on plex android trows errors on [seemingly] random series.

### ISSUE THREAD

**Issue by Cazzar** [japanesemediamanager/ShokoOnPlex#36]
When going through MyAnime I end up getting random errors when loading a series.
I have not managed to accurately replicate the issue to determine a pattern, but I do have [logs of when the error itself occurs](https://gist.github.com/Cazzar/8d26930267d37c767f35d8101cbc9b17).

My current setup if relevant:
Shoko Server V3.7.0.408 @ 192.168.1.4
Plex Server running on Arch Linux @ 192.168.1.3
Files are on a Samba server on the above linux server

**Comment by Tomara91** [comment]
I have same issue and I'm pretty sure its because the plugin is still for 3.6.0.2 and not for 3.7.x.x so all we can do is wait for some sort of update to come for the plex plugin

**Comment by ElementalCrisis** [comment]
While not the best system, the plugins (Media Portal and Plex) use the same version number as the current version in development. If there is no development on it then its version number remains the same. While in this case it does not work, it does not mean in general it will not work. 

I'm also not sure if the changes made to Shoko Server Version 3.7 are the reason either.

**Comment by maxpiva** [comment]
Cazzar: Your log show no errors, and the error are related to ssl connection probably are out of scope.
But: When you see things like this in the log:
`016-12-28 20:59:17,102 (7fba63fff700) :  DEBUG (networking:166) - Requesting 'http://192.168.1.4:8111/JMMServerPlex/GetMetadata/1/0/8/02C578F8A6109D57E73C97B3CEECA4C2'
`

Do http://192.168.1.4:8111/JMMServerPlex/GetMetadata/1/0/8/02C578F8A6109D57E73C97B3CEECA4C2 in the browser, and check the result is a valid xml or an error, in any case include JMMServer log when it happens. Since Plex plugin is a simple proxy that forward that xml to Plex. The error is probably in JMMServer.

**Comment by Cazzar** [comment]
@maxpiva I have the SSL error throwing even on successful attempts, 
though, is throwing errors on the attribute when running it through the validator: 
``3:	399	Element type "Role" must be followed by either attribute specifications, ">" or "/>".``

Since I have some time myself, I'll have a look at the current version of Shoko Server's plex part once I work out the full case.
